name: Deploy CI

on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install vsce
        run: npm install -g vsce

      - name: yarn
        run: yarn

      - name: VSCE publish
        run: vsce publish --yarn -p $env:VSCE_PAT
        env:
          VSCE_PAT: ${{ secrets.VSCE_PRETTYXML }}

      - name: Open VSX publish
        run: |
          $packageFile = (Get-ChildItem *.vsix | Sort-Object -Descending)[0]
          npx ovsx publish $packageFile.Name --yarn -p $env:OPEN_VSX_PAT
        env:
          OPEN_VSX_PAT: ${{ secrets.OPENVSX }}
